includes:
  - SuSAv2ToValenica_MEC_q0binned_all.ToolConfig.yaml
  - SuSAv2ToMartini_MEC_q0binned_all.ToolConfig.yaml
syst_providers: [SuSAv2ToValenica_MECInterp_q0binned_all, SuSAv2ToMartini_MECInterp_q0binned_all]
