// DeclaredDialTestNuSyst.cxx
// Prints an inventory of all dials declared in a nusystematics fhicl config,
// with their metadata (CV value, one-sigma shifts, variations, flags).
// Inspired by NIWGReWeight's DeclaredDialTest.

#include "systematicstools/interface/types.hh"
#include "systematicstools/utility/string_parsers.hh"

#include "fhiclcpp/ParameterSet.h"
#include "cetlib/filepath_maker.h"

#include <algorithm>
#include <array>
#include <cerrno>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <unistd.h>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

using namespace systtools;

// Robust fhicl loader: try the literal path first (handles absolute paths
// and paths relative to cwd), fall back to FHICL_FILE_PATH lookup (handles
// bare basenames). Throws fhicl::exception if neither works.
fhicl::ParameterSet LoadFhicl(const std::string &fclname) {
  try {
    cet::filepath_maker fm;
    return fhicl::ParameterSet::make(fclname, fm);
  } catch (std::exception const &) {}
  cet::filepath_lookup_nonabsolute fm("FHICL_FILE_PATH");
  return fhicl::ParameterSet::make(fclname, fm);
}

namespace cliopts {
std::string fclname;
std::vector<std::string> parameters;
std::string mode;   // empty -> no mode filter
bool verbose = false;
bool refresh = false;  // force regenerate even if cache exists
}

constexpr const char *kInventoryEnvVar = "NUSYST_INVENTORY_FCL";

// Default cache path. Resolves against the binary's OWN install prefix
// (baked in at compile time via NUSYST_INSTALL_PREFIX) so the cache always
// lands next to the binary's shipped fhicls -- regardless of whether some
// other setup script has overwritten $nusystematics_ROOT or $NUSYST in the
// user's shell. Env vars are only consulted as fallbacks for the unlikely
// case the install directory was moved post-build.
std::string InventoryDefaultPath() {
#ifdef NUSYST_INSTALL_PREFIX
  return std::string(NUSYST_INSTALL_PREFIX) + "/fcl/nusyst_inventory.fcl";
#else
  for (char const *var : {"nusystematics_ROOT", "NUSYST"}) {
    char const *val = std::getenv(var);
    if (val && *val) return std::string(val) + "/fcl/nusyst_inventory.fcl";
  }
  return "/tmp/nusyst_inventory.fcl";
#endif
}

// Map a provider's fully-qualified name to its physics mode bucket
// (CCQE / CCRES / NCEL / NCRES / RES / COH / DIS / MEC / SPP / FSI).
//
// Three rules, evaluated in order:
//   1. Hardcoded overrides for providers whose qualified name doesn't end
//      in the bucket (ZExpPCAWeighter -> CCQE, ResIso -> RES).
//   2. The GENIEReWeight_<BUCKET> convention: the substring after the last
//      underscore is the bucket.
//   3. Otherwise return an empty string (unmapped) -- the dial won't be
//      selectable by any --mode filter, only by the unfiltered view.
inline std::string ModeForProvider(const std::string &provider_fq) {
  // 1. hardcoded overrides keyed on the tool_type prefix
  if (provider_fq.rfind("ZExpPCAWeighter", 0) == 0) return "CCQE";
  if (provider_fq.rfind("ResIso", 0) == 0)         return "RES";
  // 2. GENIEReWeight_<BUCKET> convention
  auto pos = provider_fq.rfind('_');
  if (pos != std::string::npos && pos + 1 < provider_fq.size()) {
    return provider_fq.substr(pos + 1);
  }
  return "";
}

void SayUsage(char const *argv[]) {
  std::cout << "[USAGE]: " << argv[0] << "\n\n"
    "  Source of the parameter-headers fhicl, in priority order:\n"
    "    1. -c <config.fcl>            (explicit)\n"
    "    2. $" << kInventoryEnvVar << "  (env var pointing at a fhicl path)\n"
    "    3. " << InventoryDefaultPath() << "        (default cache location)\n"
    "  If the resolved fhicl does not yet exist, it is generated by shelling\n"
    "  out to `GenerateAllDialsConfigNuSyst --mode all`. Subsequent calls\n"
    "  reuse it. Pass --refresh to force regeneration.\n\n"
    "  Optional:\n"
    "    -c <config.fcl>       Inventory an existing parameter-headers fhicl\n"
    "    --mode <BUCKET>       Filter to dials whose provider maps to BUCKET.\n"
    "                          One of: CCQE, CCRES, NCEL, NCRES, RES, COH,\n"
    "                          DIS, MEC, SPP, FSI. Each provider is mapped\n"
    "                          to exactly one bucket -- FSI shows only FSI\n"
    "                          dials; CCQE includes ZExpPCAWeighter's b1..b4;\n"
    "                          RES includes ResIso.\n"
    "    -p <par1,par2,...>    Filter dials by name substring\n"
    "    --verbose             Print paramVariations, validity range, opts\n"
    "    --refresh             Force regenerate the cached fhicl\n"
    "    -?|--help             Show this message\n"
    << std::endl;
}

void HandleOpts(int argc, char const *argv[]) {
  int opt = 1;
  while (opt < argc) {
    std::string s(argv[opt]);
    if (s == "-?" || s == "--help") { SayUsage(argv); exit(0); }
    else if (s == "-c") cliopts::fclname = argv[++opt];
    else if (s == "--mode") cliopts::mode = argv[++opt];
    else if (s == "--verbose") cliopts::verbose = true;
    else if (s == "--refresh") cliopts::refresh = true;
    else if (s == "-p") {
      std::string tok; std::istringstream ss(argv[++opt]);
      while (std::getline(ss, tok, ',')) if (!tok.empty()) cliopts::parameters.push_back(tok);
    } else {
      std::cout << "[ERROR]: Unknown option: " << s << std::endl;
      SayUsage(argv); exit(1);
    }
    opt++;
  }
}

bool ParamSelected(const std::string &name) {
  if (cliopts::parameters.empty()) return true;
  for (auto &sel : cliopts::parameters)
    if (name.find(sel) != std::string::npos) return true;
  return false;
}

std::string FmtDouble(double v, int width = 8) {
  if (v == kDefaultDouble) return std::string(width - 3, ' ') + "---";
  std::ostringstream ss;
  ss << std::fixed << std::setprecision(3) << std::setw(width) << v;
  return ss.str();
}

// GenerateAllDialsConfigNuSyst writes a `_scan_report` sub-table inside
// generated_systematic_provider_configuration capturing which tool-config
// fhicls failed / were skipped, and which registered tool_types had no
// fhicl on disk at all. Surface it here so a user looking at the inventory
// can tell at a glance "this is everything I can see, this is what isn't
// showing up, this is why."
void PrintScanReportFooter(const fhicl::ParameterSet &gen) {
  fhicl::ParameterSet report;
  try {
    report = gen.get<fhicl::ParameterSet>("_scan_report");
  } catch (std::exception const &) {
    return; // older / hand-rolled fhicl without a report
  }

  auto failed_n   = report.get<std::vector<std::string>>("failed_names", {});
  auto failed_r   = report.get<std::vector<std::string>>("failed_reasons", {});
  auto sk_data_n  = report.get<std::vector<std::string>>("skipped_data_names", {});
  auto sk_data_r  = report.get<std::vector<std::string>>("skipped_data_reasons", {});
  auto sk_bug_n   = report.get<std::vector<std::string>>("skipped_bug_names", {});
  auto sk_bug_r   = report.get<std::vector<std::string>>("skipped_bug_reasons", {});
  auto sk_other_n = report.get<std::vector<std::string>>("skipped_other_names", {});
  auto sk_other_r = report.get<std::vector<std::string>>("skipped_other_reasons", {});
  auto no_fcl     = report.get<std::vector<std::string>>("registered_no_fcl", {});
  auto grw_n      = report.get<std::vector<std::string>>("genie_rw_skipped_names", {});
  auto grw_r      = report.get<std::vector<std::string>>("genie_rw_skipped_reasons", {});
  auto fcl_dir    = report.get<std::string>("fcl_dir", "");

  if (failed_n.empty() && sk_data_n.empty() && sk_bug_n.empty() &&
      sk_other_n.empty() && no_fcl.empty() && grw_n.empty()) return;

  auto print_paired = [](const char *title,
                         const std::vector<std::string> &names,
                         const std::vector<std::string> &reasons) {
    std::cout << "\n" << title << " (" << names.size() << "):\n";
    for (size_t i = 0; i < names.size(); ++i) {
      std::cout << "  " << names[i] << "\n";
      if (i < reasons.size() && !reasons[i].empty())
        std::cout << "      " << reasons[i] << "\n";
    }
  };

  std::cout << "\n=== Scan report ===\n";
  if (!fcl_dir.empty())
    std::cout << "Scanned: " << fcl_dir << " (recursive)\n";

  if (!no_fcl.empty()) {
    std::cout << "\nRegistered providers with no tool-config fhicl ("
              << no_fcl.size() << "):\n";
    for (auto const &t : no_fcl)
      std::cout << "  " << t << "\n";
    std::cout << "  -> add a fcl/<name>.ToolConfig.fcl (and an entry in "
                 "fcl/CMakeLists.txt) to surface these in the inventory.\n";
  }
  if (!failed_n.empty())
    print_paired("Tool configs that failed to load", failed_n, failed_r);
  if (!sk_data_n.empty()) {
    print_paired("Tool configs skipped - missing external data file",
                 sk_data_n, sk_data_r);
    std::cout << "  -> stage the data file referenced above and re-run with "
                 "--refresh.\n";
  }
  if (!sk_bug_n.empty()) {
    print_paired("Tool configs skipped - known upstream bug",
                 sk_bug_n, sk_bug_r);
    std::cout << "  -> these providers' tool configs are fine; the failure is\n"
                 "     in shared upstream code (likely a single null-string\n"
                 "     construction). One fix will unblock all of them. See\n"
                 "     project_basicstring_null_bug memory entry.\n";
  }
  if (!sk_other_n.empty())
    print_paired("Tool configs skipped - other reasons",
                 sk_other_n, sk_other_r);

  if (!grw_n.empty()) {
    print_paired("Inactive GENIE Reweight dials (filtered by default config)",
                 grw_n, grw_r);
    std::cout << "  -> these dials exist in GENIE Reweight but are dropped\n"
                 "     from the kitchen-sink config. The filter logic lives in\n"
                 "     GenerateAllDialsConfigNuSyst.cxx, DialInactiveReason().\n"
                 "     To re-enable any of them, write a hand-rolled tool config\n"
                 "     that names the dial explicitly and feed it to nusyst config\n"
                 "     directly, bypassing the kitchen-sink filter.\n";
  }

  std::cout << std::endl;
}

std::string FmtVariations(const std::vector<double> &vars) {
  if (vars.empty()) return "(none)";
  std::ostringstream ss;
  ss << "[";
  for (size_t i = 0; i < vars.size(); ++i) {
    if (i > 0) ss << ", ";
    ss << std::fixed << std::setprecision(3) << vars[i];
  }
  ss << "]";
  return ss.str();
}

int main(int argc, char const *argv[]) {
  HandleOpts(argc, argv);

  // Ignore SIGPIPE so that piping the output through `head` / `less` doesn't
  // kill the binary before it finishes writing.
  std::signal(SIGPIPE, SIG_IGN);

  // Resolve which fhicl to inventory. Priority:
  //   1. -c <file>                       (explicit)
  //   2. $NUSYST_INVENTORY_FCL           (env var path)
  //   3. $nusystematics_ROOT/fcl/nusyst_inventory.fcl (built-in default
  //      (or $NUSYST/fcl/..., or /tmp/... if neither var is exported)
  // If the resolved path doesn't exist on disk, shell out to
  // GenerateAllDialsConfigNuSyst to populate it; subsequent calls reuse the
  // file. --refresh forces regeneration even if the file exists.
  bool generated_now = false;
  if (cliopts::fclname.empty()) {
    char const *env = std::getenv(kInventoryEnvVar);
    if (env && *env) {
      cliopts::fclname = env;
    } else {
      cliopts::fclname = InventoryDefaultPath();
    }
  }

  bool need_generate = cliopts::refresh ||
                       (::access(cliopts::fclname.c_str(), R_OK) != 0);
  if (need_generate) {
    std::string cmd =
        "GenerateAllDialsConfigNuSyst --mode all -o " + cliopts::fclname +
        " > /dev/null 2>&1";
    int rc = std::system(cmd.c_str());
    if (rc != 0) {
      std::cerr << "[ERROR]: Auto-generation of dial config failed (rc=" << rc
                << "). Re-running with output visible for diagnosis:\n";
      std::system(("GenerateAllDialsConfigNuSyst --mode all -o " +
                   cliopts::fclname).c_str());
      return 3;
    }
    generated_now = true;
  }

  // If we just generated the cache and the env var isn't set, hint to the
  // user how to lock the path in for the rest of their shell session.
  if (generated_now && !std::getenv(kInventoryEnvVar)) {
    std::cerr << "[INFO]: Cached kitchen-sink dial fhicl at "
              << cliopts::fclname << "\n"
              << "        Subsequent `nusyst inventory` calls will reuse it. "
                 "To override the cache location:\n"
              << "          export " << kInventoryEnvVar << "="
              << cliopts::fclname << "\n"
              << "        Pass --refresh to force regeneration." << std::endl;
  }

  // Walk the fhicl directly -- no response_helper, no GENIE tune build, no
  // provider instantiation. All the fields we display are static keys in
  // the parameter-headers fhicl, so reading them straight from the
  // ParameterSet is hundreds of times faster than going through
  // response_helper (which is the path that DumpConfiguredTweaksNuSyst etc.
  // actually need because they have to evaluate per-event weights).

  fhicl::ParameterSet raw;
  try {
    raw = LoadFhicl(cliopts::fclname);
  } catch (std::exception const &e) {
    std::cerr << "[ERROR]: Failed to parse fhicl " << cliopts::fclname
              << ": " << e.what() << std::endl;
    return 4;
  }

  std::string top_key = "generated_systematic_provider_configuration";
  fhicl::ParameterSet gen;
  try {
    gen = raw.get<fhicl::ParameterSet>(top_key);
  } catch (std::exception const &e) {
    std::cerr << "[ERROR]: " << cliopts::fclname << " has no top-level key '"
              << top_key << "': " << e.what() << std::endl;
    return 4;
  }

  auto provider_names = gen.get<std::vector<std::string>>(
      "syst_providers", std::vector<std::string>{});

  // Collect rows first so we can align columns
  struct Row {
    paramId_t pid;
    std::string provider;
    std::string name;
    double cv;
    double sigma_up, sigma_down;
    int nvar;
    bool splineable, correction, natural, weight_syst;
    std::vector<double> variations;
    std::array<double, 2> validity;
    std::vector<std::string> opts;
  };
  std::vector<Row> rows;

  for (auto const &pname : provider_names) {
    fhicl::ParameterSet prov;
    try {
      prov = gen.get<fhicl::ParameterSet>(pname);
    } catch (std::exception const &) { continue; }

    std::string tool_type     = prov.get<std::string>("tool_type", "");
    std::string instance_name = prov.get<std::string>("instance_name", "");
    std::string provider_fq   = pname;  // == tool_type + "_" + instance_name

    if (!cliopts::mode.empty() && ModeForProvider(provider_fq) != cliopts::mode)
      continue;

    // Iterate the provider's keys; treat any nested ParameterSet whose
    // payload has a `prettyName` field as a dial header.
    for (auto const &key : prov.get_names()) {
      if (!prov.is_key_to_table(key)) continue;
      fhicl::ParameterSet dial;
      try { dial = prov.get<fhicl::ParameterSet>(key); }
      catch (std::exception const &) { continue; }
      if (!dial.has_key("prettyName")) continue;

      Row r;
      r.name        = dial.get<std::string>("prettyName");
      if (!ParamSelected(r.name)) continue;

      r.pid         = dial.get<paramId_t>("systParamId", -1);
      r.provider    = provider_fq;
      r.cv          = dial.get<double>("centralParamValue", kDefaultDouble);
      r.nvar        = (int)dial.get<std::vector<double>>("paramVariations", {}).size();
      r.splineable  = dial.get<bool>("isSplineable", false);
      r.correction  = dial.get<bool>("isCorrection", false);
      r.natural     = dial.get<bool>("unitsAreNatural", false);
      r.weight_syst = dial.get<bool>("isWeightSystematicVariation", true);
      r.variations  = dial.get<std::vector<double>>("paramVariations", {});
      auto sigmas   = dial.get<std::vector<double>>("oneSigmaShifts",
                                                    {kDefaultDouble, kDefaultDouble});
      r.sigma_down  = sigmas.size() > 0 ? sigmas[0] : kDefaultDouble;
      r.sigma_up    = sigmas.size() > 1 ? sigmas[1] : kDefaultDouble;
      auto validity = dial.get<std::vector<double>>("paramValidityRange",
                                                     {kDefaultDouble, kDefaultDouble});
      r.validity    = {validity.size() > 0 ? validity[0] : kDefaultDouble,
                       validity.size() > 1 ? validity[1] : kDefaultDouble};
      r.opts        = dial.get<std::vector<std::string>>("opts", {});
      rows.push_back(std::move(r));
    }
  }

  // Sort by systParamId so the output is deterministic.
  std::sort(rows.begin(), rows.end(),
            [](Row const &a, Row const &b) { return a.pid < b.pid; });

  // Footer behaviour:
  //   - full inventory (no --mode, no -p):  print the categorised scan report
  //     covering missing-fhicl / failed / skipped / inactive-GRW etc.
  //   - filtered view (--mode or -p set):   the report covers the whole config,
  //     not just the filtered bucket, so showing it would be misleading about
  //     what the user just listed. Replace it with a one-line pointer back to
  //     the unfiltered command.
  auto print_footer = [&]() {
    if (cliopts::mode.empty() && cliopts::parameters.empty()) {
      PrintScanReportFooter(gen);
    } else {
      std::cout << "\n[NOTE]: This is a subset of the available dials. "
                   "Skipped or failed dials are not shown.\n"
                   "        To see the full list, run `nusyst inventory` "
                   "without --mode / -p.\n";
    }
  };

  if (rows.empty()) {
    std::cout << "[INFO]: No dials matched the selection." << std::endl;
    print_footer();
    return 0;
  }

  // Column widths
  size_t w_id = 4, w_prov = 10, w_name = 10;
  for (auto &r : rows) {
    w_id = std::max(w_id, std::to_string(r.pid).size());
    w_prov = std::max(w_prov, r.provider.size());
    w_name = std::max(w_name, r.name.size());
  }
  w_id += 2; w_prov += 2; w_name += 2;

  // Header
  std::cout << "\n";
  std::cout << "=== Dial inventory from " << cliopts::fclname;
  if (!cliopts::mode.empty()) std::cout << "  (mode: " << cliopts::mode << ")";
  std::cout << " ===\n";
  std::cout << "Total dials: " << rows.size() << "\n\n";

  std::cout << std::left
            << std::setw(w_id) << "ID"
            << std::setw(w_prov) << "Provider"
            << std::setw(w_name) << "Name"
            << std::setw(10) << "CV"
            << std::setw(10) << "+1sigma"
            << std::setw(10) << "-1sigma"
            << std::setw(6) << "Nvar"
            << std::setw(7) << "spline"
            << std::setw(7) << "corr"
            << std::setw(7) << "units"
            << "\n";

  size_t total_w = w_id + w_prov + w_name + 10 + 10 + 10 + 6 + 7 + 7 + 7;
  std::cout << std::string(total_w, '-') << "\n";

  for (auto &r : rows) {
    std::cout << std::left
              << std::setw(w_id) << r.pid
              << std::setw(w_prov) << r.provider
              << std::setw(w_name) << r.name
              << std::setw(10) << FmtDouble(r.cv)
              << std::setw(10) << FmtDouble(r.sigma_up)
              << std::setw(10) << FmtDouble(r.sigma_down)
              << std::setw(6) << r.nvar
              << std::setw(7) << (r.splineable ? "yes" : "no")
              << std::setw(7) << (r.correction ? "yes" : "no")
              << std::setw(7) << (r.natural ? "nat" : "sigma")
              << "\n";

    if (cliopts::verbose) {
      std::cout << "    paramVariations: " << FmtVariations(r.variations) << "\n";
      std::cout << "    validityRange:   ["
                << FmtDouble(r.validity[0], 6) << ", "
                << FmtDouble(r.validity[1], 6) << "]\n";
      std::cout << "    weightSyst:      " << (r.weight_syst ? "yes" : "no (property shift)") << "\n";
      if (!r.opts.empty()) {
        std::cout << "    opts:            ";
        for (size_t i = 0; i < r.opts.size(); ++i) {
          if (i > 0) std::cout << ", ";
          std::cout << r.opts[i];
        }
        std::cout << "\n";
      }
      std::cout << "\n";
    }
  }

  std::cout << std::endl;
  print_footer();
  return 0;
}
