NOvAStyleNonResPionNorm_toolconfig:
  HighWResponse: 5e-2
  NR_nu_n_CC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_n_CC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_n_CC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_n_NC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_n_NC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_n_NC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_np_CC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_np_CC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_np_CC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_np_NC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_np_NC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_np_NC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_p_CC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_p_CC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_p_CC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_p_NC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_p_NC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nu_p_NC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_n_CC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_n_CC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_n_CC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_n_NC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_n_NC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_n_NC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_np_CC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_np_CC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_np_CC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_np_NC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_np_NC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_np_NC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_p_CC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_p_CC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_p_CC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_p_NC_1Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_p_NC_2Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  NR_nubar_p_NC_3Pi_variation_descriptor: "[-3,-2,-1,0,1,2,3]"
  OneSigmaResponse: 5e-1
  WBegin: 0
  WEnd: 5
  WTransition: 3
  fill_valid_tree: false
  instance_name: NRPiNorm
  tool_type: NOvAStyleNonResPionNorm
syst_providers: [NOvAStyleNonResPionNorm_toolconfig]
