#message(STATUS "[JSKIMDEBUG] CMAKE_SOURCE_DIR = ${CMAKE_SOURCE_DIR}")
file(GLOB DATAFILES LIST_DIRECTORIES false ${CMAKE_CURRENT_SOURCE_DIR}/*)
if(DATAFILES)
  list(REMOVE_ITEM DATAFILES ${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.txt)
  if(DATAFILES)
    install(FILES ${DATAFILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/data)
  endif()
endif()
